import * as React from 'react';
import Head from 'next/head';
import CssBaseline from '@mui/material/CssBaseline';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
// import Sidebar from './SideBar';
import {useMediaQuery} from '@mui/material';
import Header from './Header';
import MobileHeader from './MobileHeader';

export interface ILayoutProps {
    children: any;
    selectedCur: any;
    // eslint-disable-next-line no-unused-vars
    setSelectedCur: (value: any) => void;
}

export default function Layout(props: ILayoutProps) {
    const XsUp = useMediaQuery('(max-width:750px)');
    console.log('ddd', XsUp);
    return (
        <Box sx={{backgroundColor: '#ededed'}}>
            <Head>
                <title>Price Calculator</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <React.Fragment>
                    <CssBaseline />
                    <Box sx={{flexGrow: 1, width: '100%'}}>
                        {XsUp ? (
                            <MobileHeader
                                selectedCur={props.selectedCur}
                                setSelectedCur={props.setSelectedCur}
                            />
                        ) : (
                            <Header
                                selectedCur={props.selectedCur}
                                setSelectedCur={props.setSelectedCur}
                            />
                        )}
                    </Box>
                    <Container maxWidth={false} sx={{pt: 10}}>
                        <Box>{props.children}</Box>
                    </Container>
                </React.Fragment>
            </main>
        </Box>
    );
}
